name: Mirroring
on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://chrysalis-innersource@dev.azure.com/chrysalis-innersource/Azure%20Percept%20Python%20library/_git/Azure%20Percept%20IoT%20Edge%20Module'
          GIT_USERNAME: chrysalis-innersource
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}